version: '3.8'

services:
  api:
    image: ${IMAGE_API}:${TAG:-latest}
    env_file:
      - .env
    ports:
      - target: 3001
        published: ${API_PORT:-8091}
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        order: start-first
        failure_action: rollback

  web:
    image: ${IMAGE_WEB}:${TAG:-latest}
    env_file:
      - .env
    ports:
      - target: 80
        published: ${WEB_PORT:-8090}
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        order: start-first
        failure_action: rollback
